### PR TITLE
fix(iot-dev): Fix race condition where reconnection logic could carry on after client was closed

### LINKED ISSUE #1343: [Bug Report] Disconnection race condition
- **OS and version used:** Android 4.4
- **Java runtime used:** 1.6
- **SDK version used:** Java release 2020-11-16 (1.27.0) and Java release 2021-08-09 (1.32.1)

## Description of the issue
When trying to close the connection, we ran into a race condition with the SDK. The logs below show the race condition between our application successfully closing the connection (status DISCONNECTED) and the SDK restoring the connection (status DISCONNECTED_RETRYING)  

Thread ID 854 in our application called closeNow() to close  the connection but at the same time thread ID 1264 which appear to be from the SDK restored it at the same moment.  

The result is, we tried to close the connection but the SDK restored it so we are still connected. 

The logs are confusing. IotHubTransport set status to DISCONNECTED then DISCONNECTED_RETRYING.
It also print a trace about client being successfully closed but also not being able to disconnect. 

## Code sample exhibiting the issue
No specific code to provide.

## Console log of the issue
```
Timestamp            PID   TID
09-07 18:12:40.661   586   854 I DeviceClient:    Closing device client...
09-07 18:12:40.691   586   854 I IotHubTransport: Updating transport status to new status DISCONNECTED with reason CLIENT_CLOSE
09-07 18:12:40.691   586  1264 W IotHubTransport: Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK
09-07 18:12:40.691   586  1264 W IotHubTransport: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Mqtt connection lost
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connectionLost(Mqtt.java:389)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.connectionLost(CommsCallback.java:304)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:441)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at java.lang.Thread.run(Thread.java:841)
09-07 18:12:40.691   586  1264 W IotHubTransport: Caused by: Connection lost (32109) - java.io.EOFException
09-07 18:12:40.691   586  1264 W IotHubTransport: 	... 2 more
09-07 18:12:40.691   586  1264 W IotHubTransport: Caused by: java.io.EOFException
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at java.io.DataInputStream.readByte(DataInputStream.java:77)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
09-07 18:12:40.691   586  1264 W IotHubTransport: 	... 1 more
09-07 18:12:40.691   586   854 I IotHubTransport: Client connection closed successfully
09-07 18:13:40.920   586  1264 W IotHubTransport: Failed to close and re-open the iot hub transport connection, checking if another retry attempt should be made
09-07 18:13:40.920   586  1264 W IotHubTransport: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to disconnect
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.disconnect(Mqtt.java:166)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.connect(Mqtt.java:128)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:57)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:202)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:785)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:916)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:865)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:820)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:253)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:21)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at java.lang.Thread.run(Thread.java:841)
09-07 18:13:40.920   586  1264 W IotHubTransport: Caused by: Connect already in progress (32110)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms.close(ClientComms.java:237)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.close(MqttAsyncClient.java:1617)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.close(MqttAsyncClient.java:1605)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttConnection.close(MqttConnection.java:180)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.disconnect(Mqtt.java:158)
09-07 18:13:40.920   586  1264 W IotHubTransport: 	... 10 more
09-07 18:13:42.021   586  1264 I IotHubTransport: The connection to the IoT Hub has been established
09-07 18:13:42.021   586  1264 I IotHubTransport: Updating transport status to new status CONNECTED with reason CONNECTION_OK

### PR DESCRIPTION
**Pull request by timtay-microsoft**
If close is called during reconnection, it will block until the current reconnection attempt completes (successfully or not) before closing the connection and marking the local state as closed

If reconnection is initiated during a close, it will block until the close call has finished tearing down the connection and marking the local state as closed. After the close call has finished, the reconnection logic will immediately give up since the client was closed

#1343

### CODE REVIEW

File: device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java [hunk 1]
```diff
@@ -1218,6 +1230,12 @@ private void reconnect(TransportException transportException)
                 && transportException != null
                 && transportException.isRetryable())
         {
+            if (this.isClosing)
```
Comment (timtay-microsoft) [inline device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java:1233]: This check occurs in the reconnection loop, so if ```close()``` is called while this reconnection is already happening, it will block until the latest reconnection attempt completes and the thread exits before the ```close()``` call continues.

File: device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java [hunk 2]
```diff
@@ -409,6 +413,8 @@ public void open(boolean withRetry) throws TransportException
             throw new TransportException("Open cannot be called while transport is reconnecting");
         }
 
+        this.isClosing = false;
```
Comment (timtay-microsoft) [inline device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java:416]: This flag is reset to false every time the transport is opened

File: device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java [hunk 3]
```diff
@@ -487,39 +493,45 @@ public void close(IotHubConnectionStatusChangeReason reason, Throwable cause)
             throw new IllegalArgumentException("reason cannot be null");
         }
 
-        this.cancelPendingPackets();
+        this.isClosing = true;
```
Comment (timtay-microsoft) [inline device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java:496]: Set the flag outside of the synchronized block so that any currently running reconnection logic knows to give up when this flag is set to true. Then the rest of the ```close()``` code is in the synchronization block so that it waits for the reconnection logic to end before it starts

Comment (drwill-ms) [reply device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java:496]: Sounds like a good code comment

File: device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java [hunk 4]
```diff
@@ -487,39 +493,45 @@ public void close(IotHubConnectionStatusChangeReason reason, Throwable cause)
...
 
-        this.invokeCallbacks();
-
-        if (this.taskScheduler != null)
+        // Wait until no reconnection logic is taking place
+        synchronized (this.reconnectionLock)
```
Comment (drwill-ms) [inline device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java:499]: Having locks within a lock makes me worried about deadlocks. Thoughts?

Comment (timtay-microsoft) [reply device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/IotHubTransport.java:503]: Are you referring to the ```sendThreadLock``` and ```receiveThreadLock```? Neither of those locks are acquired or modified in the reconnection thread. There is no chance that the reconnection thread holds onto the sendThreadLock or receiveThreadLock while the ```close()``` thread holds the reconnectionLock so we're safe from deadlock

**Review by jamdavi — APPROVED** [review]
