### PR TITLE
fix(iot-device): Fix issue where amqp cbs auth did not proactively re…

### LINKED ISSUE #365: [Device Client] AMQP should refresh token automatically to avoid reconnection
- **OS and version used:** Windows 10 / Raspbian

- **Java runtime used:** 1.8

- **SDK version used:** 1.14.1

# Description of the issue:
When using AMQP (WS) we're seeing this exception and reconnection about 1 time every hour, as the system knows the token expiration date it should automatically try to refresh it in advance so these exceptions do not happen.

# Console log of the issue:

```
2018-11-06 08:36:35,944 AzureIoTHub [pool-18680-thread-1] DEBUG: IoTHub connection state callback, status: DISCONNECTED_RETRYING reason: BAD_CREDENTIAL
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpUnauthorizedAccessException: Token Invalid.
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertToAmqpException(AmqpsExceptionTranslator.java:87)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1161)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onLinkRemoteClose(AmqpsIotHubConnection.java:730)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
        at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:810)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-11-06 08:36:37,239 AzureIoTHub [pool-18680-thread-1] DEBUG: IoTHub connection state callback, status: CONNECTED reason: CONNECTION_OK

```

### PR DESCRIPTION
**Pull request by timtay-microsoft**
…new sas token

# Reference/Link to the issue solved with this PR (if any)
fixes #365 

# Description of the problem
cbs task does not send a proactively refreshed sas token, so amqp connection is being lost frequently even though the SDK can renew the connection ahead of time.

# Description of the solution
added to the sas-based auth providers the ability to get a renewed sas token even when the current token has not expired yet.

### CODE REVIEW

File: device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProvider.java [hunk 1]
```diff
@@ -65,14 +65,19 @@ public IotHubSasTokenHardwareAuthenticationProvider(String hostname, String gate
...
+     *                                 Use this for pre-emptively renewing sas tokens.
+
      * @throws IOException if generating the sas token from the TPM fails
      * @return The value of SasToken
      */
-    public String getRenewedSasToken() throws IOException
+    public String getRenewedSasToken(boolean proactivelyRenew) throws IOException
     {
-        if (this.sasToken.isExpired())
+        if (this.sasToken.isExpired() || (proactivelyRenew && this.shouldRefreshToken()))
```
Comment (jasmineymlo) [inline device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProvider.java]: isExpired() is check within shouldRefreshToken().  Maybe we could remove it from here...
I would prefer calling "shouldRefreshToken" alone in the All AuthenticationProviders to make the logic cleaner...  maybe passing proactivelyRenew inside shouldRefreshToken??

File: device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java [hunk 2]
```diff
@@ -123,7 +123,7 @@ public void open(Queue<DeviceClientConfig> deviceClientConfigs) throws Transport
                 SSLContext sslContext = this.config.getAuthenticationProvider().getSSLContext();
                 if (this.config.getAuthenticationType() == DeviceClientConfig.AuthType.SAS_TOKEN)
                 {
-                    this.iotHubUserPassword = this.config.getSasTokenAuthentication().getRenewedSasToken();
+                    this.iotHubUserPassword = this.config.getSasTokenAuthentication().getRenewedSasToken(false);
```
Comment (jasmineymlo) [inline device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/MqttIotHubConnection.java]: >false [](start = 105, length = 5)

just for my information, do we not renew token in mqtt before expiration?

File: device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProvider.java (hunk 1 above)
Comment (timtay-microsoft) [reply device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/auth/IotHubSasTokenHardwareAuthenticationProvider.java]: I'll see if I can implement it that way instead. I see what you are getting at.
